# NOTE: Do not edit, file was generated by jhconvert

Name: sugar
Version: 0.83.4
Release: %mkrel 1
Summary: Sugar window manager
License: GPL/LGPL
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/glucose/sugar/sugar-0.83.4.tar.bz2

Patch: sugar-0.83.4-sugar-start-script.patch
Patch1: sugar-0.83.4-sugar-hide-register-button.patch
Patch2: sugar-0.83.4-olpc-8141.patch

Requires: sugar-toolkit >= 0.83.3
Requires: sugar-artwork >= 0.83.2
Requires: python-gtksourceview  
Requires: xdpyinfo  
Requires: pygtk2.0  
Requires: GConf2  
Requires: gstreamer0.10-plugins-base  
Requires: matchbox-window-manager  
Requires: gstreamer0.10-python  
Requires: dbus  
Requires: gtk+2  
Requires: python  
Requires: python-cjson  
Requires: hal  
Requires: python-numpy  
Requires: gnome-python-desktop  

BuildRequires: intltool >= 0.33
BuildRequires: pygtk2.0-devel  
BuildRequires: libGConf2-devel  
BuildRequires: libgtk+2-devel  
BuildRequires: libpython-devel  
BuildRequires: gettext  
BuildRequires: perl-XML-Parser  

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

%description
This package contains the base modules for Sugar.
Sugar is a graphical user interface aimed at children which promotes sharing
and collaborative learning. It was introduced on the One Laptop Per Child
(OLPC) XO laptop but is useful on other devices as well.

%package emulator
Summary: The emulator for the Sugar Desktop Environment
Group: Graphical desktop/Other
Requires: %{name} = %{version}-%{release}
Requires: x11-server-xephyr
%description emulator
This package contains the Sugar emulator. It is using Xephyr
to run a Sugar environment similar to what is on the XO laptop. 

%prep
%setup -q -n sugar-0.83.4
%patch -p1
%patch1 -p1
%patch2 -p1

%build
%configure 
make 

%install
rm -rf %{buildroot}
make  \
	DESTDIR=%{buildroot} \
	install
%find_lang sugar

%clean
rm -rf %{buildroot}

%files -f sugar.lang
%defattr(-,root,root,-)
%dir %{_datadir}/sugar
%config(noreplace) %{_sysconfdir}/dbus*/system.d/*
%config(noreplace) %{_sysconfdir}/gconf/schemas/*
%{_bindir}/*
%exclude %{_bindir}/sugar-emulator
%{python_sitelib}/*
%{_datadir}/sugar/*
%{_datadir}/mime/packages/*
%{_datadir}/xsessions/sugar.desktop
%doc AUTHORS COPYING README

%files emulator
%defattr(-,root,root,-)
%{_bindir}/sugar-emulator

