# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name:		sugar
Version:	0.101.6
Release:	1
Summary:	Sugar window manager
License:	GPL/LGPL
Group:		Graphical desktop/Other
Url:		http://sugarlabs.org/

Source0:	http://download.sugarlabs.org/sources/sucrose/glucose/sugar/sugar-%{version}.tar.xz

Requires:	sugar-artwork >= 0.88.0
Requires:	dbus  
Requires:	dbus-x11  
Requires:	GConf2  
Requires:	gstreamer1.0-plugins-base  
Requires:	gstreamer1.0-python  
Requires:	gtk+3  
Requires:	gvfs  
Requires:	metacity >= 2.27.1
Requires:	python-numpy  
Requires:	openssh  
Requires:	python-gtksourceview  
Requires:	python-xklavier  
Requires:	python-simplejson  
Requires:	sugar-base >= 0.88.0
Requires:	sugar-toolkit-gtk3 >= 0.88.0
Requires:	xdpyinfo  
Requires:	xsetroot  
Requires:	python-gi

BuildRequires:	perl-XML-Parser  
BuildRequires:	autoconf  
BuildRequires:	automake  
BuildRequires:	pkgconfig(gconf-2.0)
BuildRequires:	gettext  
BuildRequires:	intltool >= 0.33
BuildRequires:	libtool  
BuildRequires:	gtk+3.0-devel  
BuildRequires:	python-devel  
BuildRequires:	sugar-base >= 0.88.0

BuildArch:	noarch

%description
This package contains the base modules for Sugar.
Sugar is a graphical user interface aimed at children which promotes sharing
and collaborative learning. It was introduced on the One Laptop Per Child
(OLPC) XO laptop but is useful on other devices as well.

%prep
%setup -q 

%build
mkdir -p m4
intltoolize -f -c
autoreconf
%define __libtoolize true
%configure
make

%install
export GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1
make DESTDIR=%{buildroot} install
export GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=
rm -rf %{buildroot}/%{_datadir}/xsessions
%find_lang sugar

install -d -m 0755 %{buildroot}/%{_sysconfdir}/X11/wmsession.d/
cat <<__EOF__ > %{buildroot}/%{_sysconfdir}/X11/wmsession.d/08sugar
NAME=Sugar
ICON=%{_datadir}/sugar/data/icons/module-about_me.svg
DESC=Sugar window manager
EXEC=%{_bindir}/sugar
SCRIPT:
exec %{_bindir}/sugar
__EOF__

%files -f sugar.lang
%doc AUTHORS COPYING 
%config %{_sysconfdir}/dbus*/system.d/*
%config %{_sysconfdir}/gconf/schemas/*
%{_bindir}/*
%{python_sitelib}/jarabe
%{_datadir}/sugar
%{_datadir}/mime/packages/*
%config %{_sysconfdir}/X11/wmsession.d/*
%{_datadir}/GConf/gsettings/sugar-schemas.convert
%{_datadir}/glib-2.0/schemas/org.sugarlabs.gschema.xml

